services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: ["qdrant_data:/qdrant/storage"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]

  api:
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    environment:
      PORT: 3000
      NODE_ENV: development
      QDRANT_URL: http://qdrant:6333
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      qdrant:
        condition: service_started
      postgres:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/v1/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10
    ports: ["3000:3000"]


volumes:
  qdrant_data: {}
  pg_data: {}
